id = "freak-lang"
name = "FREAK Language"
version = "0.1.0"
description = "FREAK language support for Zed"
authors = ["FREAK Core Team"]
repository = "https://github.com/FREAK-lang-dev/freak-editors"
schema_version = 1

[grammars.freak]
repository = "https://github.com/FREAK-lang-dev/tree-sitter-freak"
rev = "04b9106bf1af3388c1d2a6f398b7c425ad4dea58"
